apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: damiloladeborah/udagram-api-feed
        ports:
        - containerPort: 80
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: POSTGRES_USERNAME
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: awssecrets
