language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy .
  - docker tag simple-node damiloladeborah/reverseproxy:latest

  - docker --version # print the version for logging
  - docker build -t udagram-api-user .
  - docker tag simple-node damiloladeborah/udagram-api-user:latest

  - docker --version # print the version for logging
  - docker build -t udagram-api-feed .
  - docker tag simple-node damiloladeborah/udagram-api-feed:latest

  - docker --version # print the version for logging
  - docker build -t udagram-frontend .
  - docker tag simple-node damiloladeborah/udagram-frontend:local


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push damiloladeborah/reverseproxy
  - docker push damiloladeborah/udagram-api-user
  - docker push damiloladeborah/udagram-api-feed
  - docker push damiloladeborah/udagram-frontend
